/*
 * LEAKCAM (K230D + BL616) pin mux for RT-Smart, board/configs/k230d_leakcam/pinmux_config.c.
 * GENERATED by LEAKCAM firmware/k230_board/pins.py -- edit the table there, not this file.
 *
 * All VDDIO banks are on 3V3 on this board: every bank is declared 3.3 V.
 */

#include "drv_fpioa.h"

#define VOL_BANK_IO0_1     BANK_VOL_1V8_MSC   /* fixed 1.8 V (BOOT0/BOOT1) */
#define VOL_BANK0_IO2_13   BANK_VOL_3V3_MSC
#define VOL_BANK1_IO14_25  BANK_VOL_3V3_MSC   /* W25N02KV SPI NAND, 3.3 V */
#define VOL_BANK2_IO26_37  BANK_VOL_3V3_MSC
#define VOL_BANK3_IO38_49  BANK_VOL_3V3_MSC
#define VOL_BANK4_IO50_61  BANK_VOL_3V3_MSC
#define VOL_BANK5_IO62_63  BANK_VOL_3V3_MSC

/* clang-format off */
const board_pinmux_cfg_t board_pinmux_cfg[FPIOA_PIN_MAX_NUM] = {
    [0 ] = PINMUX_CFG(0, VOL_BANK_IO0_1, 1, 0, 0, 0, 2, 0), // BOOT0 strap (R64 10k to 1V8), read by the ROM
    [1 ] = PINMUX_CFG(0, VOL_BANK_IO0_1, 1, 0, 0, 0, 2, 0), // BOOT1 strap (R31 10k to GND; BL616 IO27 via RBT1 forces 1 for USB boot)
    [2 ] = PINMUX_CFG(0, VOL_BANK0_IO2_13, 1, 1, 0, 0, 4, 0), // GPIO2 K230_ALIVE heartbeat to BL616 IO01 (reset function is JTAG_TCK)
    [3 ] = PINMUX_CFG(0, VOL_BANK0_IO2_13, 1, 0, 0, 1, 4, 1), // NC
    [4 ] = PINMUX_CFG(0, VOL_BANK0_IO2_13, 1, 0, 0, 1, 4, 1), // NC
    [5 ] = PINMUX_CFG(0, VOL_BANK0_IO2_13, 1, 0, 0, 1, 4, 1), // NC
    [6 ] = PINMUX_CFG(0, VOL_BANK0_IO2_13, 1, 0, 0, 1, 4, 1), // NC
    [7 ] = PINMUX_CFG(2, VOL_BANK0_IO2_13, 1, 1, 1, 0, 7, 1), // IIC4_SCL, CAM1 (J5, CSI2), R14/R15 4.7k to 3V3
    [8 ] = PINMUX_CFG(2, VOL_BANK0_IO2_13, 1, 1, 1, 0, 7, 1), // IIC4_SDA, CAM1 (J5, CSI2)
    [9 ] = PINMUX_CFG(0, 0, 0, 0, 0, 0, 7, 1), // not bonded on K230D
    [10] = PINMUX_CFG(0, VOL_BANK0_IO2_13, 1, 0, 0, 1, 4, 1), // NC
    [11] = PINMUX_CFG(0, VOL_BANK0_IO2_13, 1, 0, 0, 1, 4, 1), // NC
    [12] = PINMUX_CFG(0, VOL_BANK0_IO2_13, 1, 0, 0, 1, 4, 1), // NC
    [13] = PINMUX_CFG(0, VOL_BANK0_IO2_13, 1, 0, 0, 1, 4, 1), // NC
    [14] = PINMUX_CFG(1, VOL_BANK1_IO14_25, 0, 1, 1, 0, 7, 1), // OSPI_CS  -> U16 W25N02KV CS# (R39 pull-up)
    [15] = PINMUX_CFG(1, VOL_BANK1_IO14_25, 0, 1, 0, 0, 7, 1), // OSPI_CLK -> U16 CLK via R42 22R
    [16] = PINMUX_CFG(1, VOL_BANK1_IO14_25, 1, 1, 0, 0, 7, 1), // OSPI_D0  <> U16 DI/IO0
    [17] = PINMUX_CFG(1, VOL_BANK1_IO14_25, 1, 1, 0, 0, 7, 1), // OSPI_D1  <> U16 DO/IO1
    [18] = PINMUX_CFG(1, VOL_BANK1_IO14_25, 1, 1, 0, 0, 7, 1), // OSPI_D2  <> U16 WP#/IO2 (R40 pull-up)
    [19] = PINMUX_CFG(1, VOL_BANK1_IO14_25, 1, 1, 0, 0, 7, 1), // OSPI_D3  <> U16 HOLD#/IO3 (R41 pull-up)
    [20] = PINMUX_CFG(0, VOL_BANK1_IO14_25, 1, 0, 0, 1, 4, 1), // NC (bank 1)
    [21] = PINMUX_CFG(0, VOL_BANK1_IO14_25, 1, 0, 0, 1, 4, 1), // NC (bank 1)
    [22] = PINMUX_CFG(0, VOL_BANK1_IO14_25, 1, 0, 0, 1, 4, 1), // NC (bank 1)
    [23] = PINMUX_CFG(0, VOL_BANK1_IO14_25, 1, 0, 0, 1, 4, 1), // NC (bank 1)
    [24] = PINMUX_CFG(0, VOL_BANK1_IO14_25, 1, 0, 0, 1, 4, 1), // NC (bank 1)
    [25] = PINMUX_CFG(0, VOL_BANK1_IO14_25, 1, 0, 0, 1, 4, 1), // NC (bank 1)
    [26] = PINMUX_CFG(0, VOL_BANK2_IO26_37, 1, 0, 0, 1, 4, 1), // NC (MMC1 pads: BOOT0=0/BOOT1=1 would try an SD card here and fail)
    [27] = PINMUX_CFG(0, VOL_BANK2_IO26_37, 1, 0, 0, 1, 4, 1), // NC (MMC1 pads: BOOT0=0/BOOT1=1 would try an SD card here and fail)
    [28] = PINMUX_CFG(0, VOL_BANK2_IO26_37, 1, 0, 0, 1, 4, 1), // NC (MMC1 pads: BOOT0=0/BOOT1=1 would try an SD card here and fail)
    [29] = PINMUX_CFG(0, VOL_BANK2_IO26_37, 1, 0, 0, 1, 4, 1), // NC (MMC1 pads: BOOT0=0/BOOT1=1 would try an SD card here and fail)
    [30] = PINMUX_CFG(0, VOL_BANK2_IO26_37, 1, 0, 0, 1, 4, 1), // NC (MMC1 pads: BOOT0=0/BOOT1=1 would try an SD card here and fail)
    [31] = PINMUX_CFG(0, VOL_BANK2_IO26_37, 1, 0, 0, 1, 4, 1), // NC (MMC1 pads: BOOT0=0/BOOT1=1 would try an SD card here and fail)
    [32] = PINMUX_CFG(0, VOL_BANK2_IO26_37, 1, 0, 0, 1, 4, 1), // NC
    [33] = PINMUX_CFG(0, VOL_BANK2_IO26_37, 1, 0, 0, 1, 4, 1), // NC
    [34] = PINMUX_CFG(0, VOL_BANK2_IO26_37, 1, 0, 0, 1, 4, 1), // NC
    [35] = PINMUX_CFG(0, VOL_BANK2_IO26_37, 1, 0, 0, 1, 4, 1), // NC
    [36] = PINMUX_CFG(0, VOL_BANK2_IO26_37, 1, 0, 0, 1, 4, 1), // NC
    [37] = PINMUX_CFG(0, VOL_BANK2_IO26_37, 1, 0, 0, 1, 4, 1), // NC
    [38] = PINMUX_CFG(1, VOL_BANK3_IO38_49, 0, 1, 0, 0, 7, 1), // UART0_TXD console -> U2 CH340X RXD (USB-C 2)
    [39] = PINMUX_CFG(1, VOL_BANK3_IO38_49, 1, 0, 0, 0, 7, 1), // UART0_RXD console <- U2 CH340X TXD
    [40] = PINMUX_CFG(1, VOL_BANK3_IO38_49, 0, 1, 0, 0, 7, 1), // UART1_TXD -> BL616 GPIO22/RXD (AI_RXD, R36 pull-up)
    [41] = PINMUX_CFG(1, VOL_BANK3_IO38_49, 1, 0, 0, 0, 7, 1), // UART1_RXD <- BL616 GPIO21/TXD (AI_TXD, R34 pull-up)
    [42] = PINMUX_CFG(0, 0, 0, 0, 0, 0, 7, 1), // not bonded on K230D
    [43] = PINMUX_CFG(0, 0, 0, 0, 0, 0, 7, 1), // not bonded on K230D
    [44] = PINMUX_CFG(0, VOL_BANK3_IO38_49, 1, 0, 0, 1, 4, 1), // NC
    [45] = PINMUX_CFG(0, VOL_BANK3_IO38_49, 1, 0, 0, 1, 4, 1), // NC
    [46] = PINMUX_CFG(0, 0, 0, 0, 0, 0, 7, 1), // not bonded on K230D
    [47] = PINMUX_CFG(0, 0, 0, 0, 0, 0, 7, 1), // not bonded on K230D
    [48] = PINMUX_CFG(3, VOL_BANK3_IO38_49, 1, 1, 1, 0, 7, 1), // IIC0_SCL, CAM2 (J4, CSI0), R17/R18 4.7k to 3V3
    [49] = PINMUX_CFG(3, VOL_BANK3_IO38_49, 1, 1, 1, 0, 7, 1), // IIC0_SDA, CAM2 (J4, CSI0)
    [50] = PINMUX_CFG(0, 0, 0, 0, 0, 0, 7, 1), // not bonded on K230D
    [51] = PINMUX_CFG(0, 0, 0, 0, 0, 0, 7, 1), // not bonded on K230D
    [52] = PINMUX_CFG(0, 0, 0, 0, 0, 0, 7, 1), // not bonded on K230D
    [53] = PINMUX_CFG(0, 0, 0, 0, 0, 0, 7, 1), // not bonded on K230D
    [54] = PINMUX_CFG(0, 0, 0, 0, 0, 0, 7, 1), // not bonded on K230D
    [55] = PINMUX_CFG(0, 0, 0, 0, 0, 0, 7, 1), // not bonded on K230D
    [56] = PINMUX_CFG(0, 0, 0, 0, 0, 0, 7, 1), // not bonded on K230D
    [57] = PINMUX_CFG(0, 0, 0, 0, 0, 0, 7, 1), // not bonded on K230D
    [58] = PINMUX_CFG(0, 0, 0, 0, 0, 0, 7, 1), // not bonded on K230D
    [59] = PINMUX_CFG(0, VOL_BANK4_IO50_61, 1, 0, 0, 1, 4, 1), // NC
    [60] = PINMUX_CFG(1, VOL_BANK4_IO50_61, 1, 1, 0, 0, 7, 1), // PWM0 -> LED_CTL1 -> U15 TPS61161 CTRL, IR chain (J2)
    [61] = PINMUX_CFG(1, VOL_BANK4_IO50_61, 1, 1, 0, 0, 7, 0), // PWM1 -> LED_CTL2 -> U14 TPS61161 CTRL, white chain (J1)
    [62] = PINMUX_CFG(0, VOL_BANK5_IO62_63, 0, 1, 0, 1, 4, 1), // GPIO62 -> J4 pin 18 CAM_IO1 (camera LED on Pi v1.3 boards): driven low
    [63] = PINMUX_CFG(0, VOL_BANK5_IO62_63, 0, 1, 0, 1, 4, 1), // GPIO63 -> J5 pin 18 CAM_IO1 (camera LED): driven low

#if FPIOA_PIN_MAX_NUM > 64   /* 72 with the PMU RTC in use */
    /* PMU IO: not used on LEAKCAM (INT4 is the R45 cold-start pull-up), left as GPIO like
     * Canaan's K230D boards */
    [64] = PMU_GPIO(GPIO64),
    [65] = PMU_GPIO(GPIO65),
    [66] = PMU_GPIO(GPIO66),
    [67] = PMU_GPIO(GPIO67),
    [68] = PMU_GPIO(GPIO68),
    [69] = PMU_GPIO(GPIO69),
    [70] = PMU_GPIO(GPIO70),
    [71] = PMU_GPIO(GPIO71),
#endif
};
/* clang-format on */

/* Run by board/pinmux.c after the GPIO driver is up (RT_BOARD_ENABLE_PINMUX selects
 * RT_BOARD_ENABLE_PIN_INIT_SEQUENCE). J4/J5 pin 18 is CAM_IO1, the red status LED on Pi v1.3
 * style camera boards: drive it low so no LED light reaches the fisheye lenses. */
static inline __attribute__((always_inline)) void board_specific_pin_init_sequence()
{
    pin_output(62, 0);
    pin_output(63, 0);
}
